[package]
name = "waifu"
version = "0.1.1"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossterm = "0.27"

