[package]
name = "waifu"
version = "0.1.5"
edition = "2021"

[dependencies]
reqwest = { version = "0.13", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
crossterm = "0.29"
zeroize = "1.7"
bytes = "1.5"